/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from "../objects/FrontWindows.glb"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(url)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.1, -0.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.66, 1, 1.75]} />
      <group position={[1.7, 0.04, -0.04]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.66, 1, 1.75]} />
      <group position={[1.7, 0.04, -0.04]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.66, 1, 1.75]} />
      <group position={[-1.46, 0.04, 0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.66, 1, 1.75]} />
      <group position={[-3.05, 0.04, 0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.66, 1, 1.75]}>
        <group position={[0.44, -0.04, 0.08]}>
          <mesh geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0004'].geometry} material={materials['WIN0003_Textures.001']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/FrontWindows.glb')



