/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from "../objects/FrontWall.glb"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(url)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[1.67, 1, 1.87]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.44, -0.04, 0.08]}>
              <group position={[-0.84, -0.02, 0.55]}>
                <mesh geometry={nodes['#WIN0003_Handle_#WIN0003_Textures_0'].geometry} material={materials.WIN0003_Textures} />
              </group>
              <mesh geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0'].geometry} material={materials.WIN0003_Textures} />
              <mesh geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0006'].geometry} material={materials.WIN0003_Textures} position={[-1.03, -0.01, -0.01]} />
            </group>
            <mesh geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0'].geometry} material={materials.WIN0003_Textures} />
          </group>
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[1.67, 1, 1.87]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.44, -0.04, 0.08]}>
              <group position={[-0.84, -0.02, 0.55]}>
                <mesh geometry={nodes['#WIN0003_Handle_#WIN0003_Textures_0001'].geometry} material={materials.WIN0003_Textures} />
              </group>
              <mesh geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0001'].geometry} material={materials.WIN0003_Textures} />
              <mesh geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0007'].geometry} material={materials.WIN0003_Textures} position={[-1.03, -0.01, -0.01]} />
            </group>
            <mesh geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0001'].geometry} material={materials.WIN0003_Textures} />
          </group>
        </group>
      </group>
      <group position={[1.74, 0, -0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.67, 1, 1.87]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.44, -0.04, 0.08]}>
              <mesh geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0002'].geometry} material={materials.WIN0003_Textures} />
            </group>
            <group position={[1.45, -0.04, 0.09]}>
              <mesh geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0004'].geometry} material={materials.WIN0003_Textures} />
            </group>
            <mesh geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0002'].geometry} material={materials.WIN0003_Textures} />
            <mesh geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0004'].geometry} material={materials.WIN0003_Textures} position={[1.01, 0, 0]} />
          </group>
        </group>
      </group>
      <group position={[1.74, 0, -0.01]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.67, 1, 1.87]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.44, -0.04, 0.08]}>
              <mesh geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0003'].geometry} material={materials.WIN0003_Textures} />
            </group>
            <group position={[1.45, -0.04, 0.09]}>
              <mesh geometry={nodes['#WIN0003_Window_#WIN0003_Textures_0005'].geometry} material={materials.WIN0003_Textures} />
            </group>
            <mesh geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0003'].geometry} material={materials.WIN0003_Textures} />
            <mesh geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0005'].geometry} material={materials.WIN0003_Textures} />
          </group>
        </group>
      </group>
      <group position={[-1.73, -0.01, -0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.67, 1, 1.87]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0006'].geometry} material={materials.WIN0003_Textures} position={[0, -0.02, 0]} />
          </group>
        </group>
      </group>
      <group position={[-1.73, -0.01, -0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.67, 1, 1.87]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['#WIN0003_Frame_#WIN0003_Textures_0007'].geometry} material={materials.WIN0003_Textures} position={[0, -0.02, 0]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/FrontWall.glb')



