/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from "../objects/Laptop.glb"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(url)
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.0013}>
        <group position={[-88.87, 0, 54.17]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh geometry={nodes.Cube002_Keys_0.geometry} material={materials.Keys} />
          <mesh geometry={nodes.Cube002_Laptop_0.geometry} material={materials.Laptop} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Laptop.glb')
