/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import url from "../objects/Me.glb"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(url)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
  actions['Armature|mixamo.com|Layer0'].play()
});


  return (
    <group scale={[0.6, 0.6, 0.6]} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001">
          <primitive object={nodes.Hips} />
          <group name="Wolf3D_Body001">
            <skinnedMesh name="Wolf3D_Body003" geometry={nodes.Wolf3D_Body003.geometry} material={materials['Wolf3D_Body.002']} skeleton={nodes.Wolf3D_Body003.skeleton} morphTargetDictionary={nodes.Wolf3D_Body003.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Body003.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Body003_1" geometry={nodes.Wolf3D_Body003_1.geometry} material={materials['Wolf3D_Eye.003']} skeleton={nodes.Wolf3D_Body003_1.skeleton} morphTargetDictionary={nodes.Wolf3D_Body003_1.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Body003_1.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Body003_2" geometry={nodes.Wolf3D_Body003_2.geometry} material={materials['Wolf3D_Skin.002']} skeleton={nodes.Wolf3D_Body003_2.skeleton} morphTargetDictionary={nodes.Wolf3D_Body003_2.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Body003_2.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Body003_3" geometry={nodes.Wolf3D_Body003_3.geometry} material={materials['Wolf3D_Outfit_Bottom.002']} skeleton={nodes.Wolf3D_Body003_3.skeleton} morphTargetDictionary={nodes.Wolf3D_Body003_3.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Body003_3.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Body003_4" geometry={nodes.Wolf3D_Body003_4.geometry} material={materials['Wolf3D_Outfit_Footwear.002']} skeleton={nodes.Wolf3D_Body003_4.skeleton} morphTargetDictionary={nodes.Wolf3D_Body003_4.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Body003_4.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Body003_5" geometry={nodes.Wolf3D_Body003_5.geometry} material={materials['Wolf3D_Outfit_Top.003']} skeleton={nodes.Wolf3D_Body003_5.skeleton} morphTargetDictionary={nodes.Wolf3D_Body003_5.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Body003_5.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Body003_6" geometry={nodes.Wolf3D_Body003_6.geometry} material={materials['Wolf3D_Teeth.003']} skeleton={nodes.Wolf3D_Body003_6.skeleton} morphTargetDictionary={nodes.Wolf3D_Body003_6.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Body003_6.morphTargetInfluences} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mix.glb')
