/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import url from "../objects/Stereo.glb"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(url)
  return (
    <group rotation={[0, -Math.PI / 2, 0]} scale={0.015} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.metalic} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['speaker-material']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['stereo-core-material']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Stereo.glb')
