/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useState, useEffect, Suspense, useRef} from "react";
import * as THREE from "three";
import { useGLTF } from '@react-three/drei'
import { useLoader } from "@react-three/fiber";
import url from "../objects/Tree.glb"
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import { Html, useProgress } from '@react-three/drei'



export default function Model({ ...props }) {
  
  const group = useRef()
  const { nodes, materials } = useGLTF(url)


  const gltf = useLoader(GLTFLoader, url)
  

  function Loader() {
    const {progress} = useProgress()
    console.log(progress)
    console.log(4)
  }


  return (
    <Suspense fallback={<Loader />}>
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1.04, 0]} scale={0.22}>
        <group position={[-0.36, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-1.19, -26.83, 1.19]} rotation={[-Math.PI, Math.PI / 2, 0]}>
              <group rotation={[-Math.PI, 0, 0]} />
            </group>
          </group>
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-1.19, 26.83, -1.19]} rotation={[Math.PI, -Math.PI / 2, 0]}>
              <group rotation={[-Math.PI, 0, 0]} />
            </group>
          </group>
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0.2]} />
        </group>
        <group rotation={[-Math.PI, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, 0, -0.2]} />
          </group>
        </group>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0.2]} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[-3.62, 3.12, -0.37]}>
              <group position={[-2.44, 10.08, -0.2]} rotation={[1.59, 0, 0.89]} scale={[0.01, 0.01, 0.03]}>
                <mesh geometry={nodes.Object_7.geometry} material={materials.Vine01} />
                <mesh geometry={nodes.Object_7_1.geometry} material={materials.cypreschauve_bark_D_COLOR_0_COLOR_0_COLOR_0} />
                <mesh geometry={nodes.Object_7_2.geometry} material={materials.CypresChauve_mousse_D_COLOR_0_COLOR_0_COLOR_0} />
                <mesh geometry={nodes.Object_7_3.geometry} material={materials.cypreschauve_needles_D_COLOR_0_COLOR_0_COLOR_0} />
                <mesh geometry={nodes.Object_7_4.geometry} material={materials.bald_cypress_03Leaves_4}/>
                <mesh geometry={nodes.Object_7_5.geometry} material={materials.CypresChauve_mousse_D_COLOR_0_COLOR_0_COLOR_0_COLOR_0_COLOR_0} />
                <mesh geometry={nodes.Object_7_6.geometry} material={materials['bald_cypress_03Leaves_4.001_COLOR_0']} />
                <mesh geometry={nodes.Object_7_7.geometry} material={materials['CypresChauve_mousse_D_COLOR_0_COLOR_0_COLOR_0_COLOR_0.001_COLOR']} />
                <mesh geometry={nodes.Object_7_8.geometry} material={materials.bald_cypress_03Branches_3} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
    </Suspense>
  )
}

useGLTF.preload('/Tree.glb')
